### ISSUE TITLE
add ABOUT page

### ISSUE THREAD

**Issue by jxmorris12** [jmojmojmo/jmojmojmo.github.io#11]

**Comment by jmojmojmo** [comment]
Thanks for building this page. Two problems to address when you can:
(See the specs doc "jmm_site_specs_about.pdf" for reference.)

1.  Text block appears top be centered in the browser, rather than anchored 200 px from the left as in specs document. 

2.  Copyright line is not anchored to bottom of page (similar problem to the issue you resolved which had been happening on the project pages where the copyright line wasn't anchored at bottom)

**Comment by jxmorris12** [comment]
should be better . you can edit the text in ~/about.md
