### ISSUE TITLE
Mobile CSS file - Need text styling for mobile version of project pages

### ISSUE THREAD

**Issue by jmojmojmo** [jmojmojmo/jmojmojmo.github.io#26]
Currently the project pages (remember how some of them have the project title and descriptive text) on mobile are just the desktop version, so the text is much too small to read. 

If I'm wrong and you have already created CSS for mobile for the project page text, please just let me know what the lines are in the code so I can trial and error as I did with the About page mobile text styles.

Or if you haven't yet written the CSS for mobile version (type size) for project pages, can you please do so, and then let me know the lines, and I'll fiddle with it as I did the About page? (The main distinction for mobile will be larger type size and linespacing; the type will be centered above the project images, just as it is now for desktop version).

See attached: These are current mobile screenshots  showing too-small (and inconsistent for some reason) type sizes for legibility on mobile.

![img_6881](https://user-images.githubusercontent.com/31120702/36819958-92c8ecd4-1cb9-11e8-835a-156e0a6cbbb2.PNG)
![img_6882](https://user-images.githubusercontent.com/31120702/36819959-92d48bac-1cb9-11e8-95a5-7303bee571ed.PNG)
![img_6883](https://user-images.githubusercontent.com/31120702/36819960-92debb72-1cb9-11e8-8c5a-07c76a7ed32f.PNG)
![img_6884](https://user-images.githubusercontent.com/31120702/36819961-92ed5830-1cb9-11e8-9b88-5820a2dbb81d.PNG)

**Comment by jxmorris12** [comment]
I changed them as an example; look here

https://github.com/jmojmojmo/jmojmojmo.github.io/commit/c1310829167449ebe8b0d33b9250e833ce269638

**Comment by jxmorris12** [comment]
these changes are specific to mobile BECAUSE they lie within the "media query" started on line 21 of the same file

`@media only screen and (max-device-width: $breakpoint-phone) {`

since this stuff is inside that it ONLY takes place when "media only screen" (honestly I don't really know what this does except that it makes sure that you're actually on a mobile device somehow) AND when the device width is less than `$breakpoint-phone`. this is set on line 4 with 

`$breakpoint-phone: 480px;` I read somewhere that's a good number

more info here https://www.w3schools.com/cssref/css3_pr_mediaquery.asp
